Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -44,6 +44,12 @@ jobs:
             echo "Code scanning error detected. Disabling pull request."
             exit 1
           fi
+          
+      - name: Check for Errors
+        if: failure()
+        run: |
+          echo "Code scanning error detected. Disabling pull request."
+          exit 1
 
   
   analyze:
